name: Integration Tests

# MySQL Native should work with the following database versions:
#  mysql:8 (Broken on MySQL 8 - see: https://github.com/mysql-d/mysql-native/issues/230)
#  mysql:5.7
#  mariadb:10

on:
  schedule:
    - cron: '30 7 1 * *'
  push:
  pull_request:

jobs:
  # mysql8-tests:
  #   name: MySQL 8 Tests ${{ matrix.compiler }}
  #   strategy:
  #     fail-fast: false
  #     # max-parallel: 2
  #     matrix:
  #       compiler:
  #         - dmd-latest
  #         - ldc-latest

  #   runs-on: ubuntu-20.04

  #   services:
  #     mysql:
  #       image: mysql:8
  #       ports: [3306]
  #       env:
  #         MYSQL_ROOT_PASSWORD: f48dfhw3Hd!Asah7i2aZ
  #         MYSQL_DATABASE: testdb
  #         MYSQL_USER: testuser
  #         MYSQL_PASSWORD: passw0rd
  #       # Set health checks to wait until mysql service has started
  #       options: >-
  #         --health-cmd "mysqladmin ping"
  #         --health-interval 10s
  #         --health-timeout 3s
  #         --health-retries 4

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install ${{ matrix.compiler }}
  #       uses: dlang-community/setup-dlang@v1
  #       with:
  #         compiler: ${{ matrix.compiler }}

  #     - name: Install dependencies on Ubuntu
  #       if: startsWith(matrix.os, 'ubuntu')
  #       run: sudo apt-get update && sudo apt-get install libevent-dev -y

  #     ## Turns out the unittest-vibe-ut tried to connect to an actualy MySQL on 172.18.0.1 so it's not
  #     ## actually a unit test at all. It's an integration test and should be pulled out from the main
  #     ## codebase into a separate sub module
  #     - name: Run unittest-vibe-ut
  #       env:
  #         MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
  #       run: |
  #         echo "host=localhost;port=$MYSQL_PORT;user=testuser;pwd=passw0rd;db=testdb" > testConnectionStr.txt
  #         dub run -c unittest-vibe-ut -- -t

  #     - name: Test (MySQL 8)
  #       working-directory: ./tests
  #       env:
  #         MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
  #       run: |
  #         dub build
  #         ./integration-tests --port=$MYSQL_PORT

  mysql57-tests:
    name: MySQL 5.7 Tests ${{ matrix.compiler }}
    strategy:
      fail-fast: false
      # max-parallel: 2
      matrix:
        compiler:
          - dmd-latest
          - ldc-latest
          - dmd-2.095.1
          - dmd-2.094.2
          - ldc-1.25.1 # eq to dmd v2.095.1
          - ldc-1.24.0 # eq to dmd v2.094.1

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        ports: [3306]
        env:
          MYSQL_ROOT_PASSWORD: f48dfhw3Hd!Asah7i2aZ
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: passw0rd
        # Set health checks to wait until mysql service has started
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 3s
          --health-retries 4

    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.compiler }}
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install libevent-dev -y

      ## Turns out the unittest-vibe-ut tried to connect to an actualy MySQL on 172.18.0.1 so it's not
      ## actually a unit test at all. It's an integration test and should be pulled out from the main
      ## codebase into a separate sub module
      - name: Run unittest-vibe-ut
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          echo "host=localhost;port=$MYSQL_PORT;user=testuser;pwd=passw0rd;db=testdb" > testConnectionStr.txt
          dub run -c unittest-vibe-ut -- -t

      - name: Test (MySQL 5.7)
        working-directory: ./tests
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          dub build
          ./integration-tests --port=$MYSQL_PORT

      - name: Test (MySQL 5.7) vibe-core
        working-directory: ./tests
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          dub build --config=use-vibe
          ./integration-tests --port=$MYSQL_PORT

  mariadb10-tests:
    name: MariaDB 10 Tests ${{ matrix.compiler }}
    strategy:
      fail-fast: false
      # max-parallel: 2
      matrix:
        compiler:
          - dmd-latest
          - ldc-latest
          - dmd-2.095.1
          - dmd-2.094.2
          - ldc-1.25.1 # eq to dmd v2.095.1
          - ldc-1.24.0 # eq to dmd v2.094.1

    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mariadb:10
        ports: [3306]
        env:
          MYSQL_ROOT_PASSWORD: f48dfhw3Hd!Asah7i2aZ
          MYSQL_DATABASE: testdb
          MYSQL_USER: testuser
          MYSQL_PASSWORD: passw0rd
        # Set health checks to wait until mysql service has started
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 3s
          --health-retries 4

    steps:
      - uses: actions/checkout@v2

      - name: Install ${{ matrix.compiler }}
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install libevent-dev -y

      ## Turns out the unittest-vibe-ut tried to connect to an actualy MySQL on 172.18.0.1 so it's not
      ## actually a unit test at all. It's an integration test and should be pulled out from the main
      ## codebase into a separate sub module
      - name: Run unittest-vibe-ut
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          echo "host=localhost;port=$MYSQL_PORT;user=testuser;pwd=passw0rd;db=testdb" > testConnectionStr.txt
          dub run -c unittest-vibe-ut -- -t

      - name: Test (mariadb 10)
        working-directory: ./tests
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          dub build
          ./integration-tests --port=$MYSQL_PORT

      - name: Test (mariadb 10) vibe-core
        working-directory: ./tests
        env:
          MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          dub build --config=use-vibe
          ./integration-tests --port=$MYSQL_PORT